pipeline {
    agent { docker { image 'python:3.10.7-alpine' } }
    stages {
        stage('run python script') {
            steps {
                sh 'python --version'
            }
        }
    }
}